name: Build, test and publish nnef

# TODO: Run this action on new tags:
#on:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'
on: [push]
# TODO: Extract the tag name: github.ref_name
# added to dist(-{os name})-{ref_name}
# maybe use olegtarasov/get-tag@v2.1.3

jobs:
  build_wheels:
    name: Build nnef wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
          - macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels for nnef
        uses: pypa/cibuildwheel@v2.17.0
        with:
          package-dir: parser
          output-dir: dist/
          config-file: parser/pyproject.toml

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.3
        id: tagName

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ steps.tagName.outputs.tag }}
          path: ./dist/*.whl


  build_sdist:
    name: Build nnef sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build ./parser/ --sdist --outdir ./dist

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.3
        id: tagName

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ steps.tagName.outputs.tag }}
          path: ./dist/*.tar.gz

  publish:
    name: Publish nnef
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist]
    steps:
      - name: Download dist/
        uses: actions/download-artifact@v4
        with:
          path: "dist"
          merge-multiple: true
      # Just for testing purposes
      - name: Test
        run: ls -R dist
